server:
  port: 8202

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.159.21:3306/shequ-sys?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 1234

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8